version: '2' 
services:
    wp-web:
        image: mauricext4fs/docker-alpine-nginx-ssl-ninezh.cc
        restart: always
        links:
          - wp-php-fpm
        volumes:
          - ./etc/nginx/wp.conf:/etc/nginx/conf.d/default.conf:cached
          - ./wordpress:/var/www/html:cached
          - ./wp-config.php:/var/www/html/wp-config.php:cached
          - ./plugins:/var/www/html/wp-content/plugins:cached
          - ./themes:/var/www/html/wp-content/themes:cached
          - ./uploads:/var/www/html/wp-content/uploads
        networks:
          www-gateway:
            aliases:
              - ${WORDPRESS_SITE_URL}
        environment:
          - VIRTUAL_HOST=${WORDPRESS_SITE_URL}
          - COMPOSE_PROJECT_NAME

    wp-php-fpm:
      image: mauricext4fs/docker-php7-alpine-imagic-openssl
      restart: always
      volumes:
        - ./wordpress:/var/www/html:cached
        - ./wp-config.php:/var/www/html/wp-config.php:cached
        - ./plugins:/var/www/html/wp-content/plugins:cached
        - ./themes:/var/www/html/wp-content/themes:cached
        - ./uploads:/var/www/html/wp-content/uploads
      networks:
          www-gateway:
      environment:
        - WORDPRESS_SITE_URL=https://${WORDPRESS_SITE_URL}/
        - WORDPRESS_DB_HOST
        - WORDPRESS_DB_USER
        - WORDPRESS_DB_PASSWORD
        - WORDPRESS_DB_NAME
        - WORDPRESS_UNIQUE_KEY
        - COMPOSE_PROJECT_NAME

networks:
  www-gateway:
    external: true
