version: '2' 
services:
    wp-web:
        image: nginx:alpine
        restart: always
        links:
          - wp-php-fpm
        volumes:
          - ./etc/nginx/options.include:/etc/nginx/options.include:cached
          - ./etc/nginx/wp.conf:/etc/nginx/conf.d/default.conf:cached
          - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
          - ./wordpress:/var/www/html:cached
          - ./wp-config.php:/var/www/html/wp-config.php:cached
          - ./plugins:/var/www/html/wp-content/plugins:cached
          - ./themes:/var/www/html/wp-content/themes:cached
          - ./uploads:/var/www/html/wp-content/uploads
        networks:
          www-gateway:
            aliases:
              - my-wordpress-site.com
        environment:
          - VIRTUAL_HOST=my-wordpress-site.com
          - VIRTUAL_PORT=80
        ports:
            - 8020:80

    wp-php-fpm:
      image: mauricext4fs/docker-php7-alpine-imagic-openssl
      restart: always
      volumes:
        - ./wordpress:/var/www/html:cached
        - ./wp-config.php:/var/www/html/wp-config.php:cached
        - ./plugins:/var/www/html/wp-content/plugins:cached
        - ./themes:/var/www/html/wp-content/themes:cached
        - ./uploads:/var/www/html/wp-content/uploads
      networks:
          www-gateway:
      environment:
        - WORDPRESS_SITE_URL=http://my-wordpress-site.com/
        - WORDPRESS_DB_HOST=my.mysql-server.com
        - WORDPRESS_DB_USER=wp
        - WORDPRESS_DB_PASSWORD=wp
        - WORDPRESS_DB_NAME=my-wordpress-site.com
        - WORDPRESS_UNIQUE_KEY=4869e5d4-bc69-vlad-9cb5-2a2ae2dbcce4

networks:
  www-gateway:
    external: true
