version: '2' 
services:
    wp-web:
        image: mauricext4fs/docker-alpine-nginx-ssl-ninezh.cc
        restart: always
        links:
          - wp-php-fpm
        volumes:
          - ./etc/nginx/wp.conf:/etc/nginx/conf.d/default.conf:cached
          - ./wordpress:/var/www/html:cached
          - ./plugins:/var/www/html/wp-content/plugins:cached
          - ./themes:/var/www/html/wp-content/themes:cached
          - ./.ssmtp.conf:/etc/ssmtp/ssmtp.conf:cached
        networks:
          www-gateway:
            aliases:
              - ${WORDPRESS_SITE_URL}
        environment:
          - VIRTUAL_HOST=${WORDPRESS_SITE_URL}
          - COMPOSE_PROJECT_NAME

    wp-php-fpm:
      image: mauricext4fs/docker-php7-alpine-imagic-openssl
      restart: always
      volumes:
        - ./wordpress:/var/www/html:cached
        - ./plugins:/var/www/html/wp-content/plugins:cached
        - ./themes:/var/www/html/wp-content/themes:cached
        - ./.ssmtp.conf:/etc/ssmtp/ssmtp.conf:cached
      networks:
          www-gateway:
      environment:
        - WORDPRESS_SITE_URL=https://${WORDPRESS_SITE_URL}/
        - DB_HOST
        - DB_USER
        - DB_PASSWORD
        - DB_NAME
        - UNIQUE_KEY
        - WP_CONTENT_DIR
        - COMPOSE_PROJECT_NAME
        - FTP_BASE
        - FTP_PLUGIN_DIR
        - FTP_CONTENT_DIR

networks:
  www-gateway:
    external: true
