version: '2' 
services:
    wp-web:
        image: nginx:alpine
        restart: always
        links:
          - wp-php-fpm
        volumes:
          - ./etc/nginx/options.include:/etc/nginx/options.include:cached
          - ./etc/nginx/wp.conf:/etc/nginx/conf.d/default.conf:cached
          - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
          - ./wordpress:/var/www/html:cached
          - ./wp-config.php:/var/www/html/wp-config.php:cached
          - ./plugins:/var/www/html/wp-content/plugins:cached
          - ./themes:/var/www/html/wp-content/themes:cached
          - ./uploads:/var/www/html/wp-content/uploads
        networks:
          www-gateway:
            aliases:
              - ${WORDPRESS_URL}
        environment:
          - VIRTUAL_HOST=${WORDPRESS_URL}
          - VIRTUAL_PORT=443,80

    wp-php-fpm:
      image: mauricext4fs/docker-php7-alpine-imagic-openssl
      restart: always
      volumes:
        - ./wordpress:/var/www/html:cached
        - ./wp-config.php:/var/www/html/wp-config.php:cached
        - ./plugins:/var/www/html/wp-content/plugins:cached
        - ./themes:/var/www/html/wp-content/themes:cached
        - ./uploads:/var/www/html/wp-content/uploads
      networks:
          www-gateway:
      environment:
        - WORDPRESS_SITE_URL=https://${WORDPRESS_URL}/
        - WORDPRESS_DB_HOST=${DB_HOST}
        - WORDPRESS_DB_USER=${DB_USER}
        - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
        - WORDPRESS_DB_NAME=${DB_NAME}
        - WORDPRESS_UNIQUE_KEY=${UNIQUE_KEY}

networks:
  www-gateway:
    external: true
