version: '2' 
services:
    wp-web:
        image: nginx:alpine
        links:
          - wp-php-fpm
        volumes:
          - ./etc/nginx/options.include:/etc/nginx/options.include:cached
          - ./etc/nginx/wp.conf:/etc/nginx/conf.d/default.conf:cached
          - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
          - ./etc/nginx/public_html:/var/www/html:cached
          - ./wordpress:/var/www/html/wp:cached
          - ./wp-config.php:/var/www/html/wp/wp-config.php:cached
          - ./plugins:/var/www/html/wp/wp-content/plugins:cached
          - ./themes:/var/www/html/wp/wp-content/themes:cached
        networks:
          www-gateway:
            aliases:
              - courtoisconsulting.com
        environment:
          - VIRTUAL_HOST=courtoisconsulting.com
          - VIRTUAL_PORT=80
        ports:
            - 8020:80

    wp-php-fpm:
      image: mauricext4fs/docker-php7-alpine-imagic-openssl
      volumes:
        - ./etc/nginx/public_html:/var/www/html:cached
        - ./wordpress:/var/www/html/wp:cached
        - ./wp-config.php:/var/www/html/wp/wp-config.php:cached
        - ./plugins:/var/www/html/wp/wp-content/plugins:cached
        - ./themes:/var/www/html/wp/wp-content/themes:cached
      networks:
          www-gateway:
      environment:
        - WORDPRESS_SITE_URL=http://courtoisconsulting.com
        - WORDPRESS_DB_HOST=other-db-master.ninezh.cc
        - WORDPRESS_DB_USER=wp
        - WORDPRESS_DB_PASSWORD=wp
        - WORDPRESS_DB_NAME=courtoisconsulting_com
        - WORDPRESS_UNIQUE_KEY=4869e5d4-bc69-vlad-9cb5-2a2ae2dbcce4

networks:
  www-gateway:
    external: true
